- name: Create docker container for Caddy
  docker_container:
    name: caddy
    image: abiosoft/caddy
    state: started
    restart_policy: always
    volumes:
      - /home/{{ ansible_user }}/config/caddy/certs/:/etc/caddycerts
      - /home/{{ ansible_user }}/config/caddy/Caddyfile:/etc/Caddyfile
    ports:
      - 80:80
      - 443:443
      - 2015:2015
    env:
      CADDYPATH: /etc/caddycerts
      ACME_AGREE: "true"
      DOMAIN: "{{ default.domain }}"

- name: Create docker container for Home Assistant Supervisor
  docker_container:
    image: homeassistant/amd64-hassio-supervisor
    name: hassio_supervisor
    privileged: true
    restart_policy: always
    security_opts:
      - seccomp:unconfined
      - apparmor:unconfined
    comparisons:
      image: ignore
      env: strict
      volumes: allow_more_present
    env:
      HOMEASSISTANT_REPOSITORY: homeassistant/qemux86-64-homeassistant
      SUPERVISOR_SHARE: /home/{{ ansible_user }}/config/
      SUPERVISOR_NAME: hassio_supervisor
      DBUS_SYSTEM_BUS_ADDRESS: unix:path=/var/run/dbus/system_bus_socket
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/{{ ansible_user }}/config/:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
