---
# Turn off modalità ospiti at 7 A.M.
#
id: 07ea5528-ccf4-49b7-8bde-2218f8136537
alias: Routine Reset Guest Mode
trigger:
  - platform: time
    at: '07:00:00'
action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.casa_ospiti
