---
# Play a sound on the Echo Dot.
#
id: 530E50AB-68B2-4F1E-81A9-AF851EF869AA
alias: Soggiorno Buzzer
trigger:
  - platform: mqtt
    topic: home/buzzer
    payload: 'on'
  - platform: state
    entity_id:
      - binary_sensor.cameretta_testiera_remote_1_bell
      - binary_sensor.cameretta_testiera_remote_2_bell
      - binary_sensor.bagno_esterno_campanello
    to: 'on'
action:
  - service: script.soggiorno_buzzer
  - service: notify.alexa_media
    data_template:
      data:
        type: announce
      message: >
        Campanello suonato da {{ trigger.to_state.attributes.friendly_name.replace("Campanello", "").strip() }}.
      target:
        - media_player.soggiorno_speaker
