---
# Manage lights just like a cinema.
#
id: 85A8521A-98FC-4C49-B617-F9C426DCA5AF
alias: Soggiorno Cinema Lights
trigger:
  - platform: state
    entity_id: media_player.soggiorno_tv
condition:
  - condition: state
    entity_id: input_boolean.soggiorno_cinema
    state: 'on'
action:
  - choose:
     - conditions:
         - condition: state
           entity_id: media_player.soggiorno_tv
           state: 'off'
       sequence:
         - service: input_boolean.turn_off
           entity_id: input_boolean.soggiorno_cinema
     - conditions:
         - condition: not
           conditions:
             - condition: state
               entity_id: media_player.soggiorno_tv
               state: 'playing'
       sequence:
         - service: light.turn_on
           entity_id: light.soggiorno_principale
    default:
      - service: light.turn_off
        entity_id: light.soggiorno
