---
# Control the movie with the light switches.
#
id: 691EC33E-BF87-4242-AB1D-60F1471C1B62
alias: Soggiorno Cinema Playback
trigger:
  - platform: state
    entity_id: light.soggiorno
condition:
  - condition: state
    entity_id: input_boolean.soggiorno_cinema
    state: 'on'
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: light.soggioron
            state: 'on'
        sequence:
          - service: media_player.media_pause
            entity_id: media_player.soggiorno_tv
    default:
      - service: media_player.media_play
        entity_id: media_player.soggiorno_tv
