---
# Play music on Sunday morning
#
id: E2296A6B-9A18-4688-8E91-B8C403F79D0E
alias: Soggiorno Sunday Music
trigger:
  - platform: state
    entity_id:
      - light.soggiorno_faretti
      - light.soggiorno_principale
    to: 'on'
condition:
  - condition: time
    after: '07:00:00'
    before: '09:30:00'
  - condition: state
    entity_id: group.family
    state: 'home'
  - condition: state
    entity_id: binary_sensor.sistema_giorno_lavorativo
    state: 'off'
action:
  - service: media_player.volume_set
    data:
      entity_id: media_player.soggiorno_speaker
      volume_level: 0.2
  - service: notify.alexa_media
    data_template:
      data:
        type: announce
      message: "Buongiorno! Metto un po' di musica"
      target:
        - media_player.soggiorno_speaker
  - service: script.turn_on
    entity_id: script.soggiorno_playlist
  # Just one time a day
  - delay: '03:00:00'
