---
# Send notification if ISS is above our house
#
id: 3785cc9a-2edc-47d8-a27a-fbb7748771d9
alias: Casa Notifica ISS
mode: single
trigger:
  - platform: state
    entity_id: binary_sensor.iss
    to: 'on'
condition:
  - condition: state
    entity_id: person.eliseo_martelli
    state: 'home'
  - condition: time
    before: '23:00:00'
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
action:
  - service: notify.mobile_app_mi_a3
    message: "Hey, se alzi lo sguardo al cielo potrai vedere la ISS! ✨🚀"
  - delay: '02:00:00'
