---
# Send a notification if there's going to be pest control.
#
id: e557f589-ee0e-41c9-9c90-875af279cb22
alias: Casa Notifica Disinfestazioni
trigger:
  - platform: state
    entity_id: binary_sensor.casa_disinfestazioni
    from: 'off'
    to: 'on'
  - platform: time
    at: '18:30:00'
condition:
  - condition: state
    entity_id: binary_sensor.casa_disinfestazioni
    state: 'on'
action:
  - service: script.sistema_text_and_announce
    data_template:
      message: "Ci saranno delle disinfestazioni. Ricordarsi di chiudere le finestre."
