---
id: 9a0db948-b631-43be-aeb3-a27327090dad
alias: Cortile Apertura Cancello
trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: "open_cortile_pedonale"
action:
  - service: lock.unlock
    entity_id: lock.cortile_pedonale
