---
# Manage lights outside.
#
id: 93473694-53E8-43C2-9259-39F32D177C26
alias: Cortile Luci
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sun.sun
    to: 'below_horizon'
  - platform: state
    entity_id: group.areas_cortile
    to: 'on'
    for:
      minutes: 15
  - platform: time
    at: '23:00:00'
  - platform: state
    entity_id: input_boolean.casa_ospiti
action:
  - choose:
        # Lights off but it's evening or bedtime
      - conditions:
          - condition: state
            entity_id: sun.sun
            state: 'below_horizon'
          - condition: time
            after: '12:00:00'
            before: '23:00:00'
        sequence:
            - service: light.turn_on
              entity_id: light.cortile_frontale
    default:
      - condition: state
        entity_id: input_boolean.casa_ospiti
        state: 'off'
      - service: homeassistant.turn_off
        entity_id: group.areas_cortile
