---
# Manage lights outside.
#
id: d72bab94-bcd0-4eec-b3a6-697ce43f8359
alias: Cortile Luci
trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sun.sun
    to: 'below_horizon'
  - platform: state
    entity_id:
      - light.cortile_piazzale
      - light.cortile_balcone
      - light.cortile_veranda
    to: 'on'
    for:
      minutes: 15
  - platform: time
    at: '23:00:00'
  - platform: state
    entity_id: input_boolean.casa_ospiti
  - platform: state
    entity_id: light.bagno_esterno_principale
    to: 'off'
    for:
      minutes: 1
action:
  - choose:
        # Lights off but it's evening or bedtime
      - conditions:
          - condition: state
            entity_id: sun.sun
            state: 'below_horizon'
          - condition: time
            after: '12:00:00'
            before: '23:00:00'
        sequence:
            - service: light.turn_on
              entity_id: light.cortile_piazzale
    default:
      - service: homeassistant.turn_off
        entity_id:
          - light.cortile_piazzale
          - light.cortile_balcone
          - light.cortile_veranda
