---
id: 74463706-b1a1-417d-8bbc-80595324d62e
alias: Sistema Shellies Firmware Notification
trigger:
  - platform: state
    entity_id: group.sistema_shelly_firmware
    to: 'on'
action:
  - service: notify.mobile_app_mi_a3
    data:
      message: "There's an update for shellies."
  - delay: '02:00:00'
