---
# Announce shelly devices.
#
id: shellies_announce
alias: 'Sistema Shellies Announce'
trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: "/6"
action:
  service: mqtt.publish
  data:
    topic: shellies/command
    payload: announce
