---
# If it's dinner/breakfast/lunch time, turn on kitchen downlights.
#
id: 0d6718e9-4f62-4468-aa7c-b6add5cc2ba9
alias: Cucina Luci Scolapiatti
trigger:
  - platform: homeassistant
    event: start
  - platform: time
    at:
      - '05:30:00'
      - '12:30:00'
      - '19:00:00'
  - platform: state
    entity_id: group.family
  - platform: state
    entity_id: light.cucina_scolapiatti
    to: 'on'
    for:
      hours: 2
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: group.family
            state: 'home'
          - condition: or
            conditions:
              - condition: time
                after: '05:30:00'
                before: '07:30:00'
              - condition: and
                conditions:
                  - condition: time
                    after: '12:30:00'
                    before: '14:30:00'
                  - condition: not
                    conditions:
                      - condition: or
                        conditions:
                          - condition: state
                            entity_id: weather.home
                            state: 'sunny'
                          - condition: state
                            entity_id: weather.home
                            state: 'partlycloudy'
              - condition: time
                after: '19:00:00'
                before: '21:00:00'
        sequence:
          - service: light.turn_on
            entity_id: light.cucina_scolapiatti
    default:
      - service: light.turn_off
        entity_id: light.cucina_scolapiatti
