---
id: 14048FD3-9B2E-4613-BF78-320E3B30DA03
alias: Bagno Esterno Luci On
trigger:
  - platform: state
    entity_id: binary_sensor.bagno_esterno_movimento
    to: 'on'
action:
  - service: light.turn_on
    entity_id: light.bagno_esterno_principale
