# lovelace_gen

- title: Impostazioni
  icon: mdi:settings
  path: settings
  cards:
    - !include
      - ../includes/header.yaml
      - title: "Impostazioni"
    - type: vertical-stack
      cards:
        - !include
          - ../includes/section.yaml
          - title: "Internet"
        - type: horizontal-stack
          cards:

            - type: custom:decluttering-card
              template: mini_graph
              variables:
                - entity_id: sensor.speedtest_upload
                - color: purple
                - name: Upload

            - type: custom:decluttering-card
              template: mini_graph
              variables:
                - entity_id: sensor.speedtest_download
                - color: red
                - name: Download

    - type: vertical-stack
      cards:
        - !include
          - ../includes/section.yaml
          - title: "AdGuard"

        - type: entities
          entities:
            - sensor.adguard_dns_queries_blocked
            - switch.adguard_filtering
            - sensor.adguard_average_processing_speed

    - type: vertical-stack
      cards:

        - !include
          - ../includes/section.yaml
          - title: "Altro"
        - type: entities
          entities:
            - binary_sensor.casa_disinfestazioni
            - binary_sensor.casa_presenza_acqua
            - binary_sensor.iss
            - input_boolean.casa_ospiti
            - input_boolean.casa_pulizia
            - sensor.sistema_temperatura_cpu
            - binary_sensor.sistema_giorno_lavorativo
            - script.sistema_update_shellies
